### ISSUE TITLE
Re-submission TODO

### ISSUE THREAD

**Issue by TanyaS08** [PoisotLab/ms_metaweb_transfer#24]
- [ ] Tone check response doc
- [ ] Check last few changes
- [ ] Update/check line numbers to match final_final draft.pdf
- [ ] Make traded changes file
- [ ] No new cover letter - right?
